targets:
  $default:
    builders:
      riverpod_generator:
        options:
          provider_name_prefix: "" # (default)
          provider_family_name_prefix: "" # (default)
          provider_name_suffix: "Provider" # (default)
          provider_family_name_suffix: "Provider" # (default)
