name: portfolio_app_flutter
description: "Like a name card."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.2
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/
