name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Setup env
        env:
          ENVKEY: ${{ secrets.ENVKEY }}
        run: |
          echo $ENVKEY > .env.keys
          mise run env:decrypt

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter build web --base-href /portfolio-app-flutter/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
